---
title: "STAT-231 Blog Project Data Wrangling"
author: "Rafael Vanin"
date: "11/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(robotstxt)
library(janitor)
library(rvest)
library(purrr)

library(sf)
library(leaflet)
library(viridis)

library(rnaturalearth)
library(sp)

library(RSelenium)
library(stringr)

# Open chrome tab to be remotely controlled by code in this file
rD <- rsDriver(browser = "chrome", verbose = FALSE, chromever = "95.0.4638.69", port = 4837L)
remDr <- rD$client
remDr$open()

rD$server$status()

#remDr$getStatus()

knitr::opts_chunk$set(echo = TRUE)
```

## Scraping with **rvest** only

```{r nces-digest-ratios}
nces_ratios_url <- "https://nces.ed.gov/programs/digest/d20/tables/dt20_314.60.asp"
paths_allowed(nces_ratios_url)

college_ratios <- nces_ratios_url %>%
  read_html() %>%
  html_element("body > div:nth-child(8) > table.tabletop.tableMain.tableWidth.tableBracketRow") %>%
  html_table() %>%
  setNames(c("state","staff_allprivate", "staff_4yr_nonprofit", "staff_2yr_nonprofit", "staff_forprofit", "faculty_allprivate", "faculty_4yr_nonprofit", "faculty_2yr_nonprfit", "facutly_forprofit", "faculty_percent_4yr_nonprofit", "faculty_percent_forprofit", "student_staff_4yr_nonprofit", "student_staff_forprofit", "student_faculty_4yr_nonprofit", "student_faculty_forprofit")) %>%
  tail(60) %>%
  head(51)

college_ratios
```

```{r nces-digest-degrees}
nces_undergrad_degrees_url <- "https://nces.ed.gov/programs/digest/d20/tables/dt20_319.30.asp"
paths_allowed(nces_undergrad_degrees_url)

undergrad_degrees <- nces_undergrad_degrees_url %>%
  read_html() %>%
  html_element("body > div:nth-child(8) > table.tabletop.tableMain.tableWidth.tableBracketRow") %>%
  html_table() %>%
  set_names(c("state", "total", "humanities", "psychology", "social_sci_hist", "natural_sci_math", "computer_sci", "engineering", "edutation", "business", "healthcare", "other")) %>%
  tail(59) %>%
  head(51)

undergrad_degrees
```

## Scraping with **RSelenium**

```{r trendgen-rselenium-appliants}
applicants_url <- "https://nces.ed.gov/ipeds/TrendGenerator/app/trend-table/10/101?trending=column&rid=6"
paths_allowed(applicants_url)

remDr$navigate(applicants_url)
tableButton <- remDr$findElement(using = "css", "#trend-table-container > div:nth-child(2) > div > a:nth-child(5)")
#NOTE: line above throws an error when ran in conjunction with the `remDr$navigate()` line, but then works fine when ran again separately
#   (may be due to RSelenium having to wait until the page fully loads before the CSS selector is recognized)
tableButton$clickElement()
#XML::htmlParse(remDr$getPageSource()[[1]])
tableElem <- remDr$findElement(using = "css", "#trend-table-container > div.mt-lg > div.st-container")
#tableElem$getElementText()

applicants_table <- remDr$getPageSource()[[1]] %>%
  read_html() %>%
  html_table() %>%
  purrr::pluck(2)
  
applicants_table_clean <- as.data.frame(t(applicants_table)) %>%
  select(V1, V8, V7, V6, V5, V4, V3, V2) %>%
  set_names(c("state", "applicants_2014", "applicants_2015", "applicants_2016", "applicants_2017", "applicants_2018", "applicants_2019", "applicants_2020")) %>%
  tail(51) %>%
  remove_rownames()

applicants_table_clean
```

```{r trendgen-rselenium-admission-rates}
admission_rate_url <- "https://nces.ed.gov/ipeds/TrendGenerator/app/trend-table/10/102?trending=column&rid=6"
paths_allowed(admission_rate_url)

remDr$navigate(admission_rate_url)
tableButton <- remDr$findElement(using = "css", "#trend-table-container > div:nth-child(2) > div > a:nth-child(5)") 
#NOTE: line above throws an error when ran in conjunction with the `remDr$navigate()` line, but then works fine when ran again separately
#   (may be due to RSelenium having to wait until the page fully loads before the CSS selector is recognized)
tableButton$clickElement()
#XML::htmlParse(remDr$getPageSource()[[1]])
tableElem <- remDr$findElement(using = "css", "#trend-table-container > div.mt-lg > div.st-container")
#tableElem$getElementText()

admission_rate_table <- remDr$getPageSource()[[1]] %>%
  read_html() %>%
  html_table() %>%
  purrr::pluck(2)
  
admission_rate_table_clean <- as.data.frame(t(admission_rate_table)) %>%
  select(V1, V8, V7, V6, V5, V4, V3, V2) %>%
  set_names(c("state", "rate_2014", "rate_2015", "rate_2016", "rate_2017", "rate_2018", "rate_2019", "rate_2020")) %>%
  tail(51) %>%
  remove_rownames()

admission_rate_table_clean
```

```{r trendgen-rselenium-yield-rate}
# yield rate = %admitted who enroll
# enrollment rate = %applicants who enroll

yield_rate_url <- "https://nces.ed.gov/ipeds/TrendGenerator/app/trend-table/10/103?trending=column&rid=6"
paths_allowed(yield_rate_url)

remDr$navigate(yield_rate_url)
tableButton <- remDr$findElement(using = "css", "#trend-table-container > div:nth-child(2) > div > a:nth-child(5)") 
#NOTE: line above throws an error when ran in conjunction with the `remDr$navigate()` line, but then works fine when ran again separately
#   (may be due to RSelenium having to wait until the page fully loads before the CSS selector is recognized)
tableButton$clickElement()
#XML::htmlParse(remDr$getPageSource()[[1]])
tableElem <- remDr$findElement(using = "css", "#trend-table-container > div.mt-lg > div.st-container")
#tableElem$getElementText()

yield_rate_table <- remDr$getPageSource()[[1]] %>%
  read_html() %>%
  html_table() %>%
  purrr::pluck(2)
  
yield_rate_table_clean <- as.data.frame(t(yield_rate_table)) %>%
  select(V1, V8, V7, V6, V5, V4, V3, V2) %>%
  set_names(c("state", "yield_2014", "yield_2015", "yield_2016", "yield_2017", "yield_2018", "yield_2019", "yield_2020")) %>%
  tail(51) %>%
  remove_rownames()

yield_rate_table_clean
```


```{r chronicle-rselenium-version}
chronicle_state_url <- "https://www.chronicle.com/article/almanac-states-2021"
paths_allowed(chronicle_state_url)

remDr$navigate(chronicle_state_url) # Open Chronicle state site
# NOTE: the website may sometimes make you do a reCAPCHA thing in the browser before opening the page, so it may be necessary to run the line above by itself 
#  (i.e. highlighting it and hitting CRTL-Enter/CMD-Return)

## Demographics

# Click on tab to bring up student demographics table 
demographics_button <- remDr$findElement(using = "css", "#aln-enroll_b")
#NOTE: line above throws an error when ran in conjunction with the `remDr$navigate()` line, but then works fine when ran again separately
#   (may be due to RSelenium having to wait until the page fully loads before the CSS selector is recognized)
demographics_button$clickElement()

# Find table using CSS selector
webTable <- remDr$findElement(using = "css", "#interactive_table > tbody")
demographics_table <- webTable$getElementText()[[1]] %>% # Get table text
  strsplit("\n") %>% # Split into rows (strings)
  unlist() %>%
  str_split("[:blank:](?=\\d)") %>% # Split rows into individual values as strings
  as.data.frame() # Create data frame from strings

demographics_table_clean <- as.data.frame(t(demographics_table)) %>% # Rows and columns are flipped when initially creating data frame
  remove_rownames() %>% # Removes row names left from initial data frame
  set_names(c("state", "total", "women", "minority", "native_american", "asian", "black", "hispanic", "pacific_islander", "white", "2+_races", "nonresident")) %>% #set column names
  filter(state != "United States") # remove overall US Data (can comment out this line if you need that data)

demographics_table_clean

#Types of institution
institution_button <- remDr$findElement(using = "css", "#aln-institutions")
institution_button$clickElement()

webTable <- remDr$findElement(using = "css", "#interactive_table > tbody")
institution_table <- webTable$getElementText()[[1]] %>%
  strsplit("\n") %>%
  unlist() %>%
  str_split("[:blank:](?=(\\d|n))") %>%
  as.data.frame()

institution_table_clean <- as.data.frame(t(institution_table)) %>%
  remove_rownames() %>%
  set_names(c("state", "total", "public_4year", "public_2year", "private_np_4yr", "private_np_2yr", "private_fp_4yr", "private_fp_2yr")) %>%
  filter(state != "United States")

institution_table_clean

#graduration rates

grad_rates_button <- remDr$findElement(using = "css", "#aln-grad")
#NOTE: line above throws an error when ran in conjunction with the `remDr$navigate()` line, but then works fine when ran again separately
#   (may be due to RSelenium having to wait until the page fully loads before the CSS selector is recognized)
grad_rates_button$clickElement()

# Find table using CSS selector
webTable <- remDr$findElement(using = "css", "#interactive_table > tbody")
grad_rates_table <- webTable$getElementText()[[1]] %>% # Get table text
  strsplit("\n") %>% # Split into rows (strings)
  unlist() %>%
  str_split("[:blank:](?=\\d)") %>% # Split rows into individual values as strings
  as.data.frame() # Create data frame from strings

grad_rates_table_clean <- as.data.frame(t(grad_rates_table)) %>% # Rows and columns are flipped when initially creating data frame
  remove_rownames() %>% # Removes row names left from initial data frame
  set_names(c("state", "all", "men", "women", "native_american", "asian", "black", "hispanic", "white", "two_more_races")) %>% #set column names
  filter(state != "United States") %>%
  mutate(
    all = as.numeric(str_extract(all, ".+(?=%)")),
    men = as.numeric(str_extract(men, ".+(?=%)")),
    women = as.numeric(str_extract(women, ".+(?=%)")),
    native_american = as.numeric(str_extract(native_american, ".+(?=%)")),
    asian = as.numeric(str_extract(asian, ".+(?=%)")),
    black = as.numeric(str_extract(black, ".+(?=%)")),
    hispanic = as.numeric(str_extract(hispanic, ".+(?=%)")),
    white = as.numeric(str_extract(white, ".+(?=%)")),
    two_more_races = as.numeric(str_extract(two_more_races, ".+(?=%)")),
  )

write.csv(grad_rates_table_clean, "data\\graduation_rates.csv")

# faculty pay

faculty_pay_button <- remDr$findElement(using = "css", "#aln-salaries_a")
#NOTE: line above throws an error when ran in conjunction with the `remDr$navigate()` line, but then works fine when ran again separately
#   (may be due to RSelenium having to wait until the page fully loads before the CSS selector is recognized)
faculty_pay_button$clickElement()

# Find table using CSS selector
webTable <- remDr$findElement(using = "css", "#interactive_table > tbody")
faculty_pay_table <- webTable$getElementText()[[1]] %>% # Get table text
  strsplit("\n") %>% # Split into rows (strings)
  unlist() %>%
  str_split("[:blank:](?=(\\$|n))") %>% # Split rows into individual values as strings
  as.data.frame() # Create data frame from strings

faculty_pay_table_clean <- as.data.frame(t(faculty_pay_table)) %>% # Rows and columns are flipped when initially creating data frame
  remove_rownames() %>% # Removes row names left from initial data frame
  set_names(c("state", "public_doctor_prof", "public_doctor_assoc", "public_doctor_assist", "public_doctor_all", "public_masters_prof", "public_masters_assoc", "public_masters_assist", "public_masters_all", "other_4yr_all", "2yr_all")) %>% #set column names
  filter(state != "United States")

# finance 

finance_button <- remDr$findElement(using = "css", "#aln-finance")
#NOTE: line above throws an error when ran in conjunction with the `remDr$navigate()` line, but then works fine when ran again separately
#   (may be due to RSelenium having to wait until the page fully loads before the CSS selector is recognized)
finance_button$clickElement()

# Find table using CSS selector
webTable <- remDr$findElement(using = "css", "#interactive_table > tbody")
finance_table <- webTable$getElementText()[[1]] %>% # Get table text
  strsplit("\n") %>% # Split into rows (strings)
  unlist() %>%
  str_split("[:blank:](?=[[:digit:]n\\+\\-\\$])") %>% # Split rows into individual values as strings
  as.data.frame() # Create data frame from strings

finance_table_clean <- as.data.frame(t(finance_table)) %>% # Rows and columns are flipped when initially creating data frame
  remove_rownames() %>% # Removes row names left from initial data frame
  set_names(c("state", "tuition_4yr_public", "tuition_4yr_private", "tuition_2yr_public", "state_funds", "state_funds_1yr_delta", "need_based_grants", "non_need_based_grants", "non_grant_aid", "total_aid")) %>% #set column names
  filter(state != "United States") %>%
  mutate(
    tuition_4yr_public = as.numeric(gsub("[,\\$]", "", tuition_4yr_public)),
    tuition_4yr_private = as.numeric(gsub("[,\\$]", "", tuition_4yr_private)),
    tuition_2yr_public = as.numeric(gsub("[,\\$]", "", tuition_2yr_public)),
    state_funds = as.numeric(gsub("[,\\$]", "", state_funds)),
    state_funds_1yr_delta = as.numeric(str_extract(state_funds_1yr_delta, ".+(?=%)")),
    need_based_grants = as.numeric(gsub("[,\\$]", "", need_based_grants)),
    non_need_based_grants = as.numeric(gsub("[,\\$]", "", non_need_based_grants)),
    non_grant_aid = as.numeric(gsub("[,\\$]", "", non_grant_aid)),
    total_aid = as.numeric(gsub("[,\\$]", "", total_aid))
  )

```

## Save to CSV files

```{r write-to-csv}
remDr$close() #close remote tab
rD$server$close()

write.csv(applicants_table_clean, "data\\applicants_per_state.csv")
write.csv(admission_rate_table_clean, "data\\admission_rates_per_state.csv")
write.csv(yield_rate_table_clean, "data\\yield_rates_per_state.csv")
write.csv(enrollment_table_clean, "data\\enrollment_per_state.csv")
write.csv(demographics_table_clean, "data\\student_demographics_per_state.csv")
write.csv(institution_table_clean, "data\\institutions_per_state.csv")

write.csv(college_ratios, "data\\student_faculty_staff_ratios_per_state.csv")
write.csv(undergrad_degrees, "data\\undergrad_degree_majors_per_state.csv")

write.csv(faculty_pay_table_clean, "data\\faculty_pay.csv")
write.csv(finance_table_clean, "data\\finance_table.csv")

```

## Additional Data wrangling

```{r enrollment-rates}
applicants <- read.csv("data\\applicants_per_state.csv") %>% 
  select(-X) %>% 
  mutate(
    applicants_2014 = as.numeric(gsub(",", "", applicants_2014)),
    applicants_2015 = as.numeric(gsub(",", "", applicants_2015)),
    applicants_2016 = as.numeric(gsub(",", "", applicants_2016)),
    applicants_2017 = as.numeric(gsub(",", "", applicants_2017)),
    applicants_2018 = as.numeric(gsub(",", "", applicants_2018)),
    applicants_2019 = as.numeric(gsub(",", "", applicants_2019)),
    applicants_2020 = as.numeric(gsub(",", "", applicants_2020))
  ) %>% 
  pivot_longer(-state, names_to = "year", values_to = "num_applicants") %>%
  mutate(year = as.integer(str_extract(year, "[:digit:]+")))

admission_rate <- read.csv("data\\admission_rates_per_state.csv") %>% 
  select(-X) %>%
  mutate(
    rate_2014 = as.numeric(str_extract(rate_2014, ".+(?=%)")),
    rate_2015 = as.numeric(str_extract(rate_2015, ".+(?=%)")),
    rate_2016 = as.numeric(str_extract(rate_2016, ".+(?=%)")),
    rate_2017 = as.numeric(str_extract(rate_2017, ".+(?=%)")),
    rate_2018 = as.numeric(str_extract(rate_2018, ".+(?=%)")),
    rate_2019 = as.numeric(str_extract(rate_2019, ".+(?=%)")),
    rate_2020 = as.numeric(str_extract(rate_2020, ".+(?=%)"))
  ) %>% 
  pivot_longer(-state, names_to = "year", values_to = "admission_rate") %>%
  mutate(year = as.integer(str_extract(year, "[:digit:]+")))

yield_rate <- read.csv("data\\yield_rates_per_state.csv") %>% 
  select(-X) %>%
  mutate(
    yield_2014 = as.numeric(str_extract(yield_2014, ".+(?=%)")),
    yield_2015 = as.numeric(str_extract(yield_2015, ".+(?=%)")),
    yield_2016 = as.numeric(str_extract(yield_2016, ".+(?=%)")),
    yield_2017 = as.numeric(str_extract(yield_2017, ".+(?=%)")),
    yield_2018 = as.numeric(str_extract(yield_2018, ".+(?=%)")),
    yield_2019 = as.numeric(str_extract(yield_2019, ".+(?=%)")),
    yield_2020 = as.numeric(str_extract(yield_2020, ".+(?=%)"))
  ) %>% 
  pivot_longer(-state, names_to = "year", values_to = "yield_rate") %>%
  mutate(year = as.integer(str_extract(year, "[:digit:]+")))

view(applicants)
view(admission_rate)
view(yield_rate)

admission_enrollment_data_full <- applicants %>%
  inner_join(admission_rate, by = c("state" = "state", "year" = "year")) %>%
  inner_join(yield_rate, by = c("state" = "state", "year" = "year")) %>%
  mutate(
    num_acceptances = round(num_applicants*(admission_rate*0.01), 0),
    num_enrolled = round(num_acceptances*(yield_rate*0.01), 0),
    enrollment_rate = round((num_enrolled/num_applicants)*100, 1)
  )

admission_enrollment_data_full

write.csv(admission_enrollment_data_full, "data\\admission_enrollment_data.csv")
```

## Wrangling for map

```{r final-wrangling-for-map}

areas_of_study <- read.csv("data/undergrad_degree_majors_per_state.csv") %>%
  select(-X) %>%
  rename(education = edutation) %>%
  mutate(
    total = as.numeric(gsub(",", "", total)),
    humanities = as.numeric(gsub(",", "", humanities)),
    psychology = as.numeric(gsub(",", "", psychology)),
    social_sci_hist = as.numeric(gsub(",", "", social_sci_hist)),
    natural_sci_math = as.numeric(gsub(",", "", natural_sci_math)),
    computer_sci = as.numeric(gsub(",", "", computer_sci)),
    engineering = as.numeric(gsub(",", "", engineering)),
    education = as.numeric(gsub(",", "", education)),
    business = as.numeric(gsub(",", "", business)),
    healthcare = as.numeric(gsub(",", "", healthcare)),
    other = as.numeric(gsub(",", "", other))
  ) %>%
  rename(
    "Total" = total,
    "Humanities" = humanities,
    "Psychology" = psychology,
    "Social Sciences\n& History" = social_sci_hist,
    "Natural Sciences\n& Mathematics" = natural_sci_math,
    "Computer Science" = computer_sci,
    "Engineering" = engineering,
    "Education" = education,
    "Business" = business,
    "Healthcare" = healthcare,
    "Other" = other
  ) %>%
  pivot_longer(-state, names_to = "major", values_to = "count")

admission_enrollment_data <- read.csv("data/admission_enrollment_data.csv") %>%
  select(state, year, admission_rate, enrollment_rate) %>%
  mutate(enrollment_rate = round(enrollment_rate, 1))

institution_types <- read.csv("data/institutions_per_state.csv") %>%
  select(-X) %>% 
  mutate(private_np_2yr = as.numeric(private_np_2yr)) %>%
  rename("Total" = total,
         "Public\n4-Year" = public_4year,
         "Public\n2-Year" = public_2year,
         "Private\nNonprofit\n4-Year" = private_np_4yr,
         "Private\nNonprofit\n2-Year" = private_np_2yr,
         "Private\nFor-Profit\n4-Year" = private_fp_4yr,
         "Private\nFor-Profit\n2-Year" = private_fp_2yr) %>%
  pivot_longer(-state, names_to = "institution_type", values_to = "count")

demographics_clustering <- read.csv("data/student_demographics_per_state.csv") %>%
  mutate(women = as.numeric(str_extract(women, ".+(?=%)")),
         minority = as.numeric(str_extract(minority, ".+(?=%)")),
         native_american = as.numeric(str_extract(native_american, ".+(?=%)")),
         asian = as.numeric(str_extract(asian, ".+(?=%)")),
         black = as.numeric(str_extract(black, ".+(?=%)")),
         hispanic = as.numeric(str_extract(hispanic, ".+(?=%)")),
         pacific_islander = as.numeric(str_extract(pacific_islander, ".+(?=%)")),
         white = as.numeric(str_extract(white, ".+(?=%)")),
         X2._races = as.numeric(str_extract(X2._races, ".+(?=%)")),
         nonresident = as.numeric(str_extract(nonresident, ".+(?=%)")))

student_demographics <- demographics_clustering %>%
  mutate(
    "Women" = women,
    "Men" = 100-Women,
    "Native\nAmerican" = native_american,
    "Asian" = asian,
    "Black" = black,
    "Hispanic" = hispanic,
    "Pacific\nIslander" = pacific_islander,
    "White" = white,
    "2 or more\nRaces" = X2._races
  ) %>%
  select(-c(X, minority, nonresident, total, women, native_american, asian, black, hispanic, pacific_islander, white, X2._races)) %>%
  pivot_longer(-state, names_to = "group", values_to = "percent")

finance_table <- read_csv("data/finance_table.csv")
  
student_aid <- finance_table %>%
  select(state, need_based_grants, non_need_based_grants, non_grant_aid, total_aid) %>% 
  rename("Need-\nBased Grants" = need_based_grants,
         "Non-Need-\nBased Grants" = non_need_based_grants, 
         "Non-Grant Aid" = non_grant_aid, 
         "Total Aid" = total_aid) %>%
  pivot_longer(-state, names_to = "aid_type", values_to = "amount")

faculty_table <- read.csv("data/faculty_pay.csv") %>%
  mutate(
    public_doctor_prof = as.numeric(gsub("[,\\$]", "", public_doctor_prof)),
    public_doctor_assoc = as.numeric(gsub("[,\\$]", "", public_doctor_assoc)),
    public_doctor_assist = as.numeric(gsub("[,\\$]", "", public_doctor_assist)),
    public_doctor_all = as.numeric(gsub("[,\\$]", "", public_doctor_all)),
    public_masters_prof = as.numeric(gsub("[,\\$]", "", public_masters_prof)),
    public_masters_assoc = as.numeric(gsub("[,\\$]", "", public_masters_assoc)),
    public_masters_assist = as.numeric(gsub("[,\\$]", "", public_masters_assist)),
    public_masters_all = as.numeric(gsub("[,\\$]", "", public_masters_all)),
    other_4yr_all = as.numeric(gsub("[,\\$]", "", other_4yr_all)),
    X2yr_all = as.numeric(gsub("[,\\$]", "", X2yr_all))
  ) %>%
  select(-X)

graduation_rates <- read_csv("data/graduation_rates.csv")

cluster_table <- demographics_clustering %>%
  left_join(finance_table, by = "state") %>%
  left_join(graduation_rates, by = "state") %>%
  left_join(faculty_table, by = "state") %>%
  select(-X)

# write to csv
write.csv(areas_of_study, "blog_map/map_data/areas_of_study.csv")
write.csv(admission_enrollment_data, "blog_map/map_data/admission_enrollment_data.csv")
write.csv(institution_types, "blog_map/map_data/institution_types.csv")
write.csv(student_demographics, "blog_map/map_data/student_demographics.csv")
write.csv(student_aid, "blog_map/map_data/student_aid.csv")
write.csv(cluster_table, "blog_map/map_data/cluster_table.csv")

```

